version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    networks:
      - app_network
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/cache

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_LOGIN}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PWD}
    networks:
      - app_network
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
      - /.docker-conf/rabbitmq/log/:/var/log/rabbitmq/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch_container
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    volumes:
      - ./esdata/:/usr/share/elasticsearch/data/
    networks:
      - app_network

  konsiwebcrawler:
    container_name: konsiwebcrawler_app
    build:
      context: .
    restart: always
    networks:
      - app_network
    ports:
      - "3000:3000"
    environment:
      REDIS_CLIENT_URL: ${REDIS_CLIENT_URL} # Redis client.
      ELASTIC_CLIENT_URL: ${ELASTIC_CLIENT_URL} # Elastic search client.
      RABBITMQ_CLIENT_URL: ${RABBITMQ_CLIENT_URL} # RabbitMQ client.
      RABBITMQ_LOGIN: ${RABBITMQ_LOGIN} # user for rabbitmq web management
      RABBITMQ_PWD: ${RABBITMQ_PWD} # password for rabbitmq web management
      PUPPETEER_PATH: ${PUPPETEER_PATH} # Puppeteer container path

    depends_on:
      - elasticsearch
      - redis
      - rabbitmq

volumes:
  cache:
    driver: local

networks:
  app_network:
    driver: bridge
